#!/bin/bash
################################################################################
#
# Bake is a shell script for running CakePHP bake script
# PHP Version 5.x
#
# CakePHP(tm) : Rapid Development Framework (http://www.cakephp.org)
# Copyright 2005-2009, Cake Software Foundation, Inc.
#
# Licensed under The MIT License
# Redistributions of files must retain the above copyright notice.
#
# @filesource
# @copyright		Copyright 2005-2009, Cake Software Foundation, Inc.
# @link				http://cakephp.org CakePHP(tm) Project
# @package			cake
# @subpackage		cake.cake.console
# @since				CakePHP(tm) v 1.2.0.5012
# @license			http://www.opensource.org/licenses/mit-license.php The MIT License
#
################################################################################
LIB=${0/%cake/}
APP=`pwd`

exec php -q ${LIB}cake.php -working "${APP}" "$@"

exit;